name: Flutter CI

on: [push, pull_request]

jobs:
  lint:
    name: "Static code analysis"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.1.0
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.3'
    - name: Generating .env file
      run: dart tools/env.dart
    - run: flutter pub get
    - name: Lint analysis
      run: flutter analyze

  run-tests:
    name: "Application tests"
    runs-on: ubuntu-latest
    needs:
      - lint

    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.3'
      - run: flutter pub get

      - name: Install lcov
        run: sudo apt install lcov

      - name: Generating .env file
        env: # set secret as an environment variable
          GMAPS_PLACES_API_KEY: ${{ secrets.GMAPS_PLACES_API_KEY }}
        run: dart tools/env.dart

      - name: Give tests script execution rights
        run: chmod +x tools/run_tests.sh

      - name: Running tests
        run: bash ./tools/run_tests.sh

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: Code coverage report
          path: coverage/html


  build-android:
    name: "Build Android apk"
    runs-on: ubuntu-latest
    needs:
      - run-tests

    steps:
    - uses: actions/checkout@v2.1.0
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.3'
    - run: flutter pub get

    - name: Generating .env file
      env: # set secret as an environment variable
        GMAPS_PLACES_API_KEY: ${{ secrets.GMAPS_PLACES_API_KEY }}
      run: dart tools/env.dart

    - name: Build Pandemia APK
      run: flutter build apk
    - uses: actions/upload-artifact@v1
      with:
        name: Pandemia.apk
        path: build/app/outputs/apk/release/app-release.apk

  build-iOS:
    name: Build iOS package
    runs-on: macos-latest
    needs:
      - run-tests

    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.3'
      - name: Generating .env file
        env: # set secret as an environment variable
          GMAPS_PLACES_API_KEY: ${{ secrets.GMAPS_PLACES_API_KEY }}
        run: dart tools/env.dart

      - name: build iOS Pandemia package
        run: flutter build ios --release --no-codesign
      - uses: actions/upload-artifact@v1
        with:
          name: Pandemia.app
          path: build/ios/iphoneos/Runner.app